# Generated by Django 4.2.1 on 2023-10-19 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chimedAi_web", "0002_alter_users_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_link",
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="videos/"
            ),
            preserve_default=False,
        ),
    ]
