# Generated by Django 4.2.1 on 2023-10-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chimedAi_web", "0003_remove_video_video_link_video_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video",
            new_name="video_l",
        ),
    ]
