# Generated by Django 4.2.1 on 2023-11-17 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chimedAi_web", "0004_rename_video_video_video_l"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_l",
        ),
        migrations.AddField(
            model_name="video",
            name="video_link",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
