# Generated by Django 4.2.1 on 2023-11-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chimedAi_web", "0005_remove_video_video_l_video_video_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_link",
            new_name="youtube_id",
        ),
    ]
