# Generated by Django 4.2.1 on 2023-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chimedAi_web", "0006_rename_video_link_video_youtube_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
